### ISSUE TITLE
Make numpy and matplotlib optional dependencies

### ISSUE THREAD

**Issue by sponsfreixes** [Peilonrayz/dice_stats#1]
From what I see, numpy is only used for the `plot_wireframes` function, and matplotlib is only used to build the documentation.

What do you think of making them optional dependencies? If agreed, I can come with a proposal and PR.

**Comment by Peilonrayz** [comment]
Hey, yeah that sounds fine. 👍

I remember debating whether I want the `plot_wireframes` function at all. It's got no documentation and is janky, but for now I want to keep it. A simple change to not import it should be sufficient, as then if you need it you can just `import dice_stats.display`.
